# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: steven@stevenjohn.co
author_name: Steven John
data_format: string
file_extension: ''
has_binder: true
has_settings: true
kind: frontend
labextension_name: squawk
mimetype: ''
mimetype_name: ''
project_short_description: A Copilot extension for JupyterLab.
python_name: squawk
repository: https://github.com/StevenJPx2/squawk.git
test: true
viewer_name: ''

